version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./ui
      dockerfile: dockerfile
    ports:
      - "8080:8080"
